name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.16
        uses: actions/setup-node@v2
        with:
          node-version: 18.16
      - run: npm ci

      - name: Run tests
        run: npm run test
