name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.16
        uses: actions/setup-node@v2
        with:
          node-version: 18.16

      - name: Install dependencies
        run: npm i

      - name: Run Integration Tests
        run: npm run test:main

      - name: Run Unit Tests - IPFS Lib
        run: npm run test:ipfsupload

      - name: Run Unit Tests - Smart Contract
        run: npm run test:ipfsstorage
